### ISSUE TITLE
There are more airports to this package than currently described

### ISSUE THREAD

**Issue by gilbertohasnofb** [FGMEMBERS-SCENERY/SBPK-fg-CustomScenery#1]
There are more airports to this package than what is described in this repository (currently only SBBR SBGO SBVT SBSJ SBGR)

The complete list is:

SBBR -  Presidente Jucelino Jubitsch Brasilia
SBGO - Santo Genoveva Goiania
SBVT -  Goiabeiras Vitoria
SBSJ - Base Embraer Sao Jose Dos Campos
SBGR - Guarulhos Sao Paulo
SBSP - Congonhas Sao Paulo
SBKP - Campinas Viracopos
SBGL - Galeao Rio De Janeiro
SBRJ - Santos Dummont Rio De Janeiro
SBBH - Pampulha Belo Horizonte
SBCF - Confins Belo Horizonte
SBFL - Hercillo Luz Florianopolis
SBCT - Afonso Pena Curitiba
SBPA - Salgado Filho Porto Alegre
SBCO - Canoas Rio Grande Do Sul
SBNF - Ministro Victor Konder Navegantes
SBSV - Deputado Luis Eduardo Salvador
SBPV -Governador Jorge Teixeira Porto Velho
SBTE -  Senador Petronio Portella Teresina
SBSL - Marechal Cunha Machado Sao Luis
SBRF - Aeroporto Internacional Recife
SBJP - Presidente Castro Pinto Joao Pessoa
SBMO - Zumbi Dos Palmares Maceio
SBAR - Santa Maria Aracaju
SBNT - Augusto Severo Natal
SBPJ - Tocantins Palmas
SBEG - Eduardo Gomes Manaus
SBIL - Ilheus
SBFI - Cataratas Foz Do Iguaçu
SBFZ - Pinto Martins Fortaleza
SBCY -  Marechal Rondon Cuiaba
SBCX - Campo Dos BugresCaxias Do Sul
SBCG - Campo Grande
SBCA - Cascavel
SBAQ - Araraquara
SBPK- Pelotas

**Comment by FGDATA** [comment]
Solved: Used all the ICAOS you provided in the description. Thanks for collecting this info Gilberto :dart:

**Comment by gilbertohasnofb** [comment]
My pleasure!
